apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: app-deployment
  template:
    metadata:
     labels:
      app: app-deployment
    spec:
      containers:
       - name: hello-world
         image: harel1978/flask:1.0
         ports:
           - containerPort: 5000

